name: Storm CMS User
description: Defines the user configurations, roles & permissions.
recipes:
  - core/recipes/content_editor_role
  - core/recipes/user_picture
install:
  - flood_control
  - password_policy
  - password_policy_length
  - password_policy_username
config:
  import:
    flood_control: "*"
  actions:
    user.role.anonymous:
      grantPermissions:
        - "access content"
        - "access user profiles"
        - "view media"
    user.role.authenticated:
      grantPermissions:
        - "access content"
        - "access user profiles"
        - "change own username"
    user.role.content_editor:
      grantPermissionsForEachMediaType:
        - "create %bundle media"
        - "delete any %bundle media"
        - "edit any %bundle media"
      grantPermissionsForEachNodeType:
        - "clone %bundle content"
        - "create %bundle content"
        - "delete any %bundle content"
        - "edit any %bundle content"
        - "view %bundle revisions"
      grantPermissionsForEachTaxonomyVocabulary:
        - "create terms in %bundle"
        - "edit terms in %bundle"
      grantPermissions:
        - "access administration pages"
        - "access block library"
        - "access content overview"
        - "access content_browser entity browser pages"
        - "access contextual links"
        - "access files overview"
        - "access help pages"
        - "access media overview"
        - "access navigation"
        - "access responsive preview"
        - "access sitemap"
        - "access site in maintenance mode"
        - "access user profiles"
        - "add section library templates"
        - "administer blocks"
        - "administer block content"
        - "administer menu"
        - "administer nodes"
        - "bypass advanced aggregation"
        - "bypass honeypot protection"
        - "bypass node access"
        - "change own username"
        - "create and edit custom blocks"
        - "delete section library templates"
        - "edit section library templates"
        - "import template from section library"
        - "mark as hidden in editoria11y"
        - "mark as ok in editoria11y"
        - "run cron jobs"
        - "schedule publishing of nodes"
        - "use text format rich_text"
        - "use editorial transition archive"
        - "use editorial transition archived_draft"
        - "use editorial transition archived_published"
        - "use editorial transition create_new_draft"
        - "use editorial transition publish"
        - "view any unpublished content"
        - "view editoria11y checker"
        - "view own unpublished content"
        - "view own unpublished media"
        - "view scheduled content"
        - "view section library templates"
        - "view the administration theme"
    user.role.site_maintainer:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      createIfNotExists:
        id: site_maintainer
        label: "Site Maintainer"
        weight: 3
        is_admin: false
        permissions:
          - "access administration pages"
          - "access content overview"
          - "access contextual links"
          - "access environment indicator"
          - "access files overview"
          - "access help pages"
          - "access media overview"
          - "access navigation"
          - "access responsive preview"
          - "access site in maintenance mode"
          - "access user profiles"
          - "administer blocks"
          - "administer google_tag_container"
          - "administer menu"
          - "administer nodes"
          - "bypass advanced aggregation"
          - "bypass honeypot protection"
          - "bypass node access"
          - "change own username"
          - "flood unblock ips"
          - "import configuration"
          - "mark as hidden in editoria11y"
          - "mark as ok in editoria11y"
          - "run cron jobs"
          - "synchronize configuration"
          - "use text format rich_text"
          - "view any unpublished content"
          - "view cron jobs"
          - "view editoria11y checker"
          - "view own unpublished content"
          - "view own unpublished media"
          - "view the administration theme"
          - "view user email addresses"
