name: Storm CMS User
description: Defines the user configurations, roles & permissions.
install:
  - flood_control
  - password_policy
  - password_policy_length
  - password_policy_username
config:
  import:
    flood_control: "*"
  actions:
    user.role.anonymous:
      grantPermissions:
        - "access content"
        - "access user profiles"
        - "view media"
    user.role.authenticated:
      grantPermissions:
        - "access content"
        - "access user profiles"
        - "change own username"
    user.role.content_editor:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      ensure_exists:
        id: content_editor
        label: 'Content editor'
        weight: 2
        is_admin: false
      grantPermissionsForEachMediaType:
        - 'create %bundle media'
        - 'delete any %bundle media'
        - 'edit any %bundle media'
      grantPermissionsForEachNodeType:
        - 'clone %bundle content'
        - 'create %bundle content'
        - 'delete %bundle revisions'
        - 'delete any %bundle content'
        - 'edit any %bundle content'
      grantPermissionsForEachTaxonomyVocabulary:
        - 'create terms in %bundle'
        - 'edit terms in %bundle'
      grantPermissions:
        - "access administration pages"
        - "access content overview"
        - "access contextual links"
        - "access files overview"
        - "access help pages"
        - "access media overview"
        - "access navigation"
        - "access responsive preview"
        - "access site in maintenance mode"
        - "access user profiles"
        - "administer blocks"
        - "administer menu"
        - "administer nodes"
        - "bypass honeypot protection"
        - "bypass node access"
        - "change own username"
        - "mark as hidden in editoria11y"
        - "mark as ok in editoria11y"
        - "run cron jobs"
        - "use text format rich_text"
        - "view editoria11y checker"
        - "view own unpublished content"
        - "view own unpublished media"
        - "view the administration theme"
    user.role.site_maintainer:
      # If this role already exists, then this action has no effect. If it doesn't exist, we'll create it with the following values.
      ensure_exists:
        id: site_maintainer
        label: 'Site Maintainer'
        weight: 3
        is_admin: false
        permissions:
          - "access administration pages"
          - "access content overview"
          - "access contextual links"
          - "access files overview"
          - "access help pages"
          - "access media overview"
          - "access navigation"
          - "access responsive preview"
          - "access site in maintenance mode"
          - "access user profiles"
          - "administer blocks"
          - "administer menu"
          - "administer nodes"
          - "bypass honeypot protection"
          - "bypass node access"
          - "change own username"
          - "mark as hidden in editoria11y"
          - "mark as ok in editoria11y"
          - "run cron jobs"
          - "use text format rich_text"
          - "view all media revisions"
          - "view all revisions"
          - "view cron jobs"
          - "view editoria11y checker"
          - "view own unpublished content"
          - "view own unpublished media"
          - "view the administration theme"
          - "view user email addresses"
